version: '3.8'

services:
  gmail-api-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
      # These will be overridden by .env file or environment variables
      - SENDER_EMAIL=${SENDER_EMAIL}
      - RECEIVER_EMAIL=${RECEIVER_EMAIL}
      - APP_PASSWORD=${APP_PASSWORD}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 